import { describe, it, expect } from 'vitest';
import { markdownBlocksOf, markdownLineToDocxText, blockToAnchorParagraphs } from './markdown-anchor.js';

/**
 * Anchoring inverts document-parser.ts emission: headings `## x`, ordered
 * items `1. x` (numbers injected from numbering.xml), bullets `- x`, plain
 * paragraphs verbatim, tables as GFM pipes, consecutive list lines joined by
 * single newlines. Fixtures below mirror REAL extractor output shapes.
 */

describe('markdownBlocksOf', () => {
  it('splits on blank lines, keeping list groups and tables as single blocks', () => {
    const md = '## 6 Rollout\n\nFirst paragraph text.\n\n1. step one\n2. step two\n  - nested note\n\n| a | b |\n| --- | --- |\n| 1 | 2 |\n\nTail para.';
    const blocks = markdownBlocksOf(md);
    expect(blocks.map(b => b.kind)).toEqual(['plain', 'plain', 'list', 'table', 'plain']);
    expect(blocks[2].lines).toEqual(['1. step one', '2. step two', '  - nested note']);
  });

  it('keeps fenced code with internal blank lines as one block', () => {
    const md = 'Intro.\n\n```\nline\n\nafter blank\n```\n\nOutro.';
    const blocks = markdownBlocksOf(md);
    expect(blocks).toHaveLength(3);
    expect(blocks[1].text).toContain('after blank');
  });

  it('handles empty and whitespace-only input', () => {
    expect(markdownBlocksOf('')).toEqual([]);
    expect(markdownBlocksOf('\n\n  \n')).toEqual([]);
  });
});

describe('markdownLineToDocxText', () => {
  it('strips heading markers to the docx paragraph text', () => {
    expect(markdownLineToDocxText('### 6.2 Rollout plan')).toBe('6.2 Rollout plan');
  });
  it('strips list markers including injected ordered numbers and nesting indent', () => {
    expect(markdownLineToDocxText('12. Deploy to prod')).toBe('Deploy to prod');
    expect(markdownLineToDocxText('  - nested bullet')).toBe('nested bullet');
    expect(markdownLineToDocxText('- plain bullet')).toBe('plain bullet');
  });
  it('strips inline decorations that replacements may carry', () => {
    expect(markdownLineToDocxText('The **bold** and *italic* `code` [label](http://x) mix')).toBe('The bold and italic code label mix');
  });
  it('squashes whitespace like docxParagraphText', () => {
    expect(markdownLineToDocxText('  spaced   out\ttext ')).toBe('spaced out text');
  });
  it('leaves plain paragraphs verbatim', () => {
    expect(markdownLineToDocxText('Design tenets guide every decision.')).toBe('Design tenets guide every decision.');
  });
});

describe('blockToAnchorParagraphs', () => {
  it('returns one anchor per list item', () => {
    const [block] = markdownBlocksOf('1. alpha step\n2. beta step');
    expect(blockToAnchorParagraphs(block)).toEqual(['alpha step', 'beta step']);
  });
  it('returns a single anchor for headings and plain paragraphs', () => {
    const blocks = markdownBlocksOf('## Goals\n\nBody text here.');
    expect(blockToAnchorParagraphs(blocks[0])).toEqual(['Goals']);
    expect(blockToAnchorParagraphs(blocks[1])).toEqual(['Body text here.']);
  });
  it('refuses tables', () => {
    const [table] = markdownBlocksOf('| a | b |\n| --- | --- |\n| 1 | 2 |');
    expect(table.kind).toBe('table');
    expect(blockToAnchorParagraphs(table)).toBeNull();
  });
});

describe('MCP-converter markdown dialect (live find 2026-08-26)', () => {
  // BotBoy-built docs read back through the SharePoint MCP converter carry
  // underscore italics and escaped literal punctuation ("1\\. freeze").
  it('strips underscore emphasis and unescapes literal punctuation', () => {
    expect(markdownLineToDocxText('This was **generated by BotBoy** from markdown with _no template_.'))
      .toBe('This was generated by BotBoy from markdown with no template.');
    expect(markdownLineToDocxText('1\\. freeze the schema')).toBe('1. freeze the schema');
    expect(markdownLineToDocxText('__bold__ and _italic_ mix')).toBe('bold and italic mix');
  });
  it('treats literal bullet glyphs as list markers', () => {
    expect(markdownLineToDocxText('• catalog identity unification')).toBe('catalog identity unification');
  });
  it('keeps snake_case words intact (underscore italics must not eat identifiers)', () => {
    expect(markdownLineToDocxText('the work_item_rejections table')).toBe('the work_item_rejections table');
  });
});
